"""empty message

Revision ID: 9e8e0cac900c
Revises: 
Create Date: 2022-06-06 18:46:07.793057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e8e0cac900c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Ingredient')
    op.add_column('StudentList', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('StudentList', 'StudentId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('StudentList', sa.Column('StudentId', sa.INTEGER(), nullable=False))
    op.drop_column('StudentList', 'id')
    op.create_table('Ingredient',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ingredient', sa.VARCHAR(length=64), nullable=True),
    sa.Column('created_datetime', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingredient')
    )
    # ### end Alembic commands ###
